Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  vm_settings = {
    memory: 2048,
    cpus: 2
  }
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo swapoff -a
    sudo sed -i '/swap/d' /etc/fstab
  SHELL

  config.vm.define "k8s-master" do |master|
    master.vm.network "private_network", ip: "10.0.0.10"
    master.vm.hostname = "k8s-master"
    master.vm.network "forwarded_port", guest: 30080, host: 30080, protocol: "tcp"
    # master.vm.network "forwarded_port", guest: 80, host: 80, protocol: "tcp"
    # master.vm.network "forwarded_port", guest: 443, host: 443, protocol: "tcp"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = vm_settings[:memory]
      vb.cpus = vm_settings[:cpus]
    end
  end

  (1..2).each do |i|
    config.vm.define "k8s-worker-#{i}" do |worker|
      worker.vm.network "private_network", ip: "10.0.0.1#{i}"
      worker.vm.hostname = "k8s-worker-#{i}"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = 3072
        vb.cpus = 1
      end
    end
  end

  config.vm.define "ansible-controller" do |ansible|
      ansible.vm.network "private_network", ip: "10.0.0.20"
      ansible.vm.hostname = "ansible-controller"
      ansible.vm.provider "virtualbox" do |vb|
        vb.memory = vm_settings[:memory]
        vb.cpus = 1
      end
      ansible.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install -y ansible
        sudo apt install -y sshpass
      SHELL
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "10.0.0.10 k8s-master" | sudo tee -a /etc/hosts
    echo "10.0.0.11 k8s-worker-1" | sudo tee -a /etc/hosts
    echo "10.0.0.12 k8s-worker-2" | sudo tee -a /etc/hosts
    echo "10.0.0.20 ansible-controller" | sudo tee -a /etc/hosts
  SHELL
end
