apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: eventgate
spec:
  selector:
    app: api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
  type: NodePort
