---
- name: Initialize Kubeadm on Master Node to Setup Control Plane
  hosts: k8s_master
  become: yes
  vars:
    POD_CIDR: "192.168.0.0/16"
  tasks:
    - name: Initialize Kubeadm on the master node
      command: kubeadm init --apiserver-advertise-address={{ ansible_host }} \
        --apiserver-cert-extra-sans={{ ansible_host }} \
        --pod-network-cidr={{ POD_CIDR }} \
        --node-name={{ ansible_hostname }} \
        --ignore-preflight-errors=Swap
      register: kubeadm_init_output

    - name: Save the kubeadm join command for workers
      copy:
        content: "{{ kubeadm_init_output.stdout }}"
        dest: /tmp/kubeadm_join_command.txt

- name: Configure Kubeconfig for Current User
  hosts: k8s_master
  vars:
    kube_config_path: "{{ ansible_env.HOME }}/.kube"
  tasks:
    - name: Ensure .kube directory exists
      command: mkdir -p {{ kube_config_path }}

    - name: Copy admin.conf to .kube/config
      command: sudo cp -i /etc/kubernetes/admin.conf {{ kube_config_path }}/config

    - name: Set ownership of .kube/config
      shell: sudo chown $(id -u):$(id -g) {{ kube_config_path }}/config

